version: '3.8'

services:
  web:
    build: .
    volumes:
      - app_socket:/app
    expose:
      - "8000" 
    command: ["gunicorn", "-c", "gunicorn_config.py", "app:app"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - app_socket:/app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  app_socket:
